name: TestForward

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04']
        python-version: ['3.9', '3.10']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: test-forward-pip-${{ hashFiles('requirements-test-forward.txt', '.github/workflows/test_forward.yml') }}
        restore-keys: test-forward-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel==0.37.1
        pip install Cython==0.29.28
        pip install setuptools==41.2.0
        pip install -r requirements-test-forward.txt

    - name: Invoke Test
      run: inv test --cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: coverage.xml
        fail_ci_if_error: false
        verbose: true